name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Upstream
        run: |
          git remote add upstream https://github.com/g12777/easy-TVframework-go.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main 